version: '3.8'

services:
  marksforest-admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - BOOKMARKS_FILE_PATH=/app/json/marksforest.json
    volumes:
      - ../json:/app/json:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: marksforest-network
    external: false